// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.30.2
// source: dao.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "model";

/** DAO 调用载荷，oneof 中每个字段对应一种 DAO 操作。 */
export interface DaoCall {
  call:
    | { $case: "init"; value: DaoInit }
    | { $case: "publicJoin"; value: DaoPublicJoin }
    | { $case: "join"; value: DaoJoin }
    | { $case: "leave"; value: DaoLeave }
    | { $case: "leaveWithBurn"; value: DaoLeaveWithBurn }
    | { $case: "submitProposal"; value: DaoSubmitProposal }
    | { $case: "depositProposal"; value: DaoDepositProposal }
    | { $case: "submitVote"; value: DaoSubmitVote }
    | { $case: "cancelVote"; value: DaoCancelVote }
    | { $case: "unlock"; value: DaoUnlock }
    | { $case: "execProposal"; value: DaoExecProposal }
    | { $case: "cancelProposal"; value: DaoCancelProposal }
    | { $case: "transfer"; value: DaoTransfer }
    | { $case: "approve"; value: DaoApprove }
    | { $case: "transferFrom"; value: DaoTransferFrom }
    | { $case: "spend"; value: DaoSpend }
    | { $case: "payout"; value: DaoPayout }
    | { $case: "setPublicJoin"; value: DaoSetPublicJoin }
    | { $case: "addTrack"; value: DaoAddTrack }
    | { $case: "setDefaultTrack"; value: DaoSetDefaultTrack }
    | undefined;
}

/** 成员 + 余额（u128 为 16 字节大端） */
export interface DaoMember {
  account: Uint8Array;
  balance: Uint8Array;
}

export interface DaoTrackData {
  name: string;
  preparePeriod: number;
  maxDeciding: number;
  confirmPeriod: number;
  decisionPeriod: number;
  minEnactmentPeriod: number;
  decisionDeposit: Uint8Array;
  maxBalance: Uint8Array;
}

export interface DaoCallContent {
  contract: Uint8Array;
  selector: Uint8Array;
  input: Uint8Array;
  amount: Uint8Array;
  refTimeLimit: number;
  allowReentry: boolean;
}

export interface DaoInit {
  initialMembers: DaoMember[];
  publicJoin: boolean;
  sudoAccount: Uint8Array;
  defaultTrack: DaoTrackData | undefined;
}

export interface DaoPublicJoin {
}

export interface DaoJoin {
  newUser: Uint8Array;
  balance: Uint8Array;
}

export interface DaoLeave {
}

export interface DaoLeaveWithBurn {
}

export interface DaoSubmitProposal {
  call: DaoCallContent | undefined;
  trackId: number;
}

export interface DaoDepositProposal {
  proposalId: number;
  amount: Uint8Array;
}

export interface DaoSubmitVote {
  proposalId: number;
  opinionYes: boolean;
  lockAmount: Uint8Array;
}

export interface DaoCancelVote {
  voteId: number;
}

export interface DaoUnlock {
  voteId: number;
}

export interface DaoExecProposal {
  proposalId: number;
}

export interface DaoCancelProposal {
  proposalId: number;
}

export interface DaoTransfer {
  to: Uint8Array;
  value: Uint8Array;
}

export interface DaoApprove {
  spender: Uint8Array;
  value: Uint8Array;
}

export interface DaoTransferFrom {
  from: Uint8Array;
  to: Uint8Array;
  value: Uint8Array;
}

export interface DaoSpend {
  to: Uint8Array;
  amount: Uint8Array;
  trackId: number;
}

export interface DaoPayout {
  spendId: number;
}

export interface DaoSetPublicJoin {
  publicJoin: boolean;
}

export interface DaoAddTrack {
  track: DaoTrackData | undefined;
}

export interface DaoSetDefaultTrack {
  trackId: number;
}

function createBaseDaoCall(): DaoCall {
  return { call: undefined };
}

export const DaoCall: MessageFns<DaoCall> = {
  encode(message: DaoCall, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.call?.$case) {
      case "init":
        DaoInit.encode(message.call.value, writer.uint32(10).fork()).join();
        break;
      case "publicJoin":
        DaoPublicJoin.encode(message.call.value, writer.uint32(18).fork()).join();
        break;
      case "join":
        DaoJoin.encode(message.call.value, writer.uint32(26).fork()).join();
        break;
      case "leave":
        DaoLeave.encode(message.call.value, writer.uint32(34).fork()).join();
        break;
      case "leaveWithBurn":
        DaoLeaveWithBurn.encode(message.call.value, writer.uint32(42).fork()).join();
        break;
      case "submitProposal":
        DaoSubmitProposal.encode(message.call.value, writer.uint32(50).fork()).join();
        break;
      case "depositProposal":
        DaoDepositProposal.encode(message.call.value, writer.uint32(58).fork()).join();
        break;
      case "submitVote":
        DaoSubmitVote.encode(message.call.value, writer.uint32(66).fork()).join();
        break;
      case "cancelVote":
        DaoCancelVote.encode(message.call.value, writer.uint32(74).fork()).join();
        break;
      case "unlock":
        DaoUnlock.encode(message.call.value, writer.uint32(82).fork()).join();
        break;
      case "execProposal":
        DaoExecProposal.encode(message.call.value, writer.uint32(90).fork()).join();
        break;
      case "cancelProposal":
        DaoCancelProposal.encode(message.call.value, writer.uint32(98).fork()).join();
        break;
      case "transfer":
        DaoTransfer.encode(message.call.value, writer.uint32(106).fork()).join();
        break;
      case "approve":
        DaoApprove.encode(message.call.value, writer.uint32(114).fork()).join();
        break;
      case "transferFrom":
        DaoTransferFrom.encode(message.call.value, writer.uint32(122).fork()).join();
        break;
      case "spend":
        DaoSpend.encode(message.call.value, writer.uint32(130).fork()).join();
        break;
      case "payout":
        DaoPayout.encode(message.call.value, writer.uint32(138).fork()).join();
        break;
      case "setPublicJoin":
        DaoSetPublicJoin.encode(message.call.value, writer.uint32(146).fork()).join();
        break;
      case "addTrack":
        DaoAddTrack.encode(message.call.value, writer.uint32(154).fork()).join();
        break;
      case "setDefaultTrack":
        DaoSetDefaultTrack.encode(message.call.value, writer.uint32(162).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoCall {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoCall();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.call = { $case: "init", value: DaoInit.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.call = { $case: "publicJoin", value: DaoPublicJoin.decode(reader, reader.uint32()) };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.call = { $case: "join", value: DaoJoin.decode(reader, reader.uint32()) };
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.call = { $case: "leave", value: DaoLeave.decode(reader, reader.uint32()) };
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.call = { $case: "leaveWithBurn", value: DaoLeaveWithBurn.decode(reader, reader.uint32()) };
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.call = { $case: "submitProposal", value: DaoSubmitProposal.decode(reader, reader.uint32()) };
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.call = { $case: "depositProposal", value: DaoDepositProposal.decode(reader, reader.uint32()) };
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.call = { $case: "submitVote", value: DaoSubmitVote.decode(reader, reader.uint32()) };
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.call = { $case: "cancelVote", value: DaoCancelVote.decode(reader, reader.uint32()) };
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.call = { $case: "unlock", value: DaoUnlock.decode(reader, reader.uint32()) };
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.call = { $case: "execProposal", value: DaoExecProposal.decode(reader, reader.uint32()) };
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.call = { $case: "cancelProposal", value: DaoCancelProposal.decode(reader, reader.uint32()) };
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.call = { $case: "transfer", value: DaoTransfer.decode(reader, reader.uint32()) };
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.call = { $case: "approve", value: DaoApprove.decode(reader, reader.uint32()) };
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.call = { $case: "transferFrom", value: DaoTransferFrom.decode(reader, reader.uint32()) };
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.call = { $case: "spend", value: DaoSpend.decode(reader, reader.uint32()) };
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.call = { $case: "payout", value: DaoPayout.decode(reader, reader.uint32()) };
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.call = { $case: "setPublicJoin", value: DaoSetPublicJoin.decode(reader, reader.uint32()) };
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.call = { $case: "addTrack", value: DaoAddTrack.decode(reader, reader.uint32()) };
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.call = { $case: "setDefaultTrack", value: DaoSetDefaultTrack.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoCall>, I>>(base?: I): DaoCall {
    return DaoCall.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoCall>, I>>(object: I): DaoCall {
    const message = createBaseDaoCall();
    switch (object.call?.$case) {
      case "init": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "init", value: DaoInit.fromPartial(object.call.value) };
        }
        break;
      }
      case "publicJoin": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "publicJoin", value: DaoPublicJoin.fromPartial(object.call.value) };
        }
        break;
      }
      case "join": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "join", value: DaoJoin.fromPartial(object.call.value) };
        }
        break;
      }
      case "leave": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "leave", value: DaoLeave.fromPartial(object.call.value) };
        }
        break;
      }
      case "leaveWithBurn": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "leaveWithBurn", value: DaoLeaveWithBurn.fromPartial(object.call.value) };
        }
        break;
      }
      case "submitProposal": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "submitProposal", value: DaoSubmitProposal.fromPartial(object.call.value) };
        }
        break;
      }
      case "depositProposal": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "depositProposal", value: DaoDepositProposal.fromPartial(object.call.value) };
        }
        break;
      }
      case "submitVote": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "submitVote", value: DaoSubmitVote.fromPartial(object.call.value) };
        }
        break;
      }
      case "cancelVote": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "cancelVote", value: DaoCancelVote.fromPartial(object.call.value) };
        }
        break;
      }
      case "unlock": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "unlock", value: DaoUnlock.fromPartial(object.call.value) };
        }
        break;
      }
      case "execProposal": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "execProposal", value: DaoExecProposal.fromPartial(object.call.value) };
        }
        break;
      }
      case "cancelProposal": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "cancelProposal", value: DaoCancelProposal.fromPartial(object.call.value) };
        }
        break;
      }
      case "transfer": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "transfer", value: DaoTransfer.fromPartial(object.call.value) };
        }
        break;
      }
      case "approve": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "approve", value: DaoApprove.fromPartial(object.call.value) };
        }
        break;
      }
      case "transferFrom": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "transferFrom", value: DaoTransferFrom.fromPartial(object.call.value) };
        }
        break;
      }
      case "spend": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "spend", value: DaoSpend.fromPartial(object.call.value) };
        }
        break;
      }
      case "payout": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "payout", value: DaoPayout.fromPartial(object.call.value) };
        }
        break;
      }
      case "setPublicJoin": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "setPublicJoin", value: DaoSetPublicJoin.fromPartial(object.call.value) };
        }
        break;
      }
      case "addTrack": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "addTrack", value: DaoAddTrack.fromPartial(object.call.value) };
        }
        break;
      }
      case "setDefaultTrack": {
        if (object.call?.value !== undefined && object.call?.value !== null) {
          message.call = { $case: "setDefaultTrack", value: DaoSetDefaultTrack.fromPartial(object.call.value) };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseDaoMember(): DaoMember {
  return { account: new Uint8Array(0), balance: new Uint8Array(0) };
}

export const DaoMember: MessageFns<DaoMember> = {
  encode(message: DaoMember, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.account.length !== 0) {
      writer.uint32(10).bytes(message.account);
    }
    if (message.balance.length !== 0) {
      writer.uint32(18).bytes(message.balance);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoMember {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.account = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.balance = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoMember>, I>>(base?: I): DaoMember {
    return DaoMember.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoMember>, I>>(object: I): DaoMember {
    const message = createBaseDaoMember();
    message.account = object.account ?? new Uint8Array(0);
    message.balance = object.balance ?? new Uint8Array(0);
    return message;
  },
};

function createBaseDaoTrackData(): DaoTrackData {
  return {
    name: "",
    preparePeriod: 0,
    maxDeciding: 0,
    confirmPeriod: 0,
    decisionPeriod: 0,
    minEnactmentPeriod: 0,
    decisionDeposit: new Uint8Array(0),
    maxBalance: new Uint8Array(0),
  };
}

export const DaoTrackData: MessageFns<DaoTrackData> = {
  encode(message: DaoTrackData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.preparePeriod !== 0) {
      writer.uint32(16).uint32(message.preparePeriod);
    }
    if (message.maxDeciding !== 0) {
      writer.uint32(24).uint32(message.maxDeciding);
    }
    if (message.confirmPeriod !== 0) {
      writer.uint32(32).uint32(message.confirmPeriod);
    }
    if (message.decisionPeriod !== 0) {
      writer.uint32(40).uint32(message.decisionPeriod);
    }
    if (message.minEnactmentPeriod !== 0) {
      writer.uint32(48).uint32(message.minEnactmentPeriod);
    }
    if (message.decisionDeposit.length !== 0) {
      writer.uint32(58).bytes(message.decisionDeposit);
    }
    if (message.maxBalance.length !== 0) {
      writer.uint32(66).bytes(message.maxBalance);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoTrackData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoTrackData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.preparePeriod = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxDeciding = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.confirmPeriod = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.decisionPeriod = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.minEnactmentPeriod = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.decisionDeposit = reader.bytes();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.maxBalance = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoTrackData>, I>>(base?: I): DaoTrackData {
    return DaoTrackData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoTrackData>, I>>(object: I): DaoTrackData {
    const message = createBaseDaoTrackData();
    message.name = object.name ?? "";
    message.preparePeriod = object.preparePeriod ?? 0;
    message.maxDeciding = object.maxDeciding ?? 0;
    message.confirmPeriod = object.confirmPeriod ?? 0;
    message.decisionPeriod = object.decisionPeriod ?? 0;
    message.minEnactmentPeriod = object.minEnactmentPeriod ?? 0;
    message.decisionDeposit = object.decisionDeposit ?? new Uint8Array(0);
    message.maxBalance = object.maxBalance ?? new Uint8Array(0);
    return message;
  },
};

function createBaseDaoCallContent(): DaoCallContent {
  return {
    contract: new Uint8Array(0),
    selector: new Uint8Array(0),
    input: new Uint8Array(0),
    amount: new Uint8Array(0),
    refTimeLimit: 0,
    allowReentry: false,
  };
}

export const DaoCallContent: MessageFns<DaoCallContent> = {
  encode(message: DaoCallContent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contract.length !== 0) {
      writer.uint32(10).bytes(message.contract);
    }
    if (message.selector.length !== 0) {
      writer.uint32(18).bytes(message.selector);
    }
    if (message.input.length !== 0) {
      writer.uint32(26).bytes(message.input);
    }
    if (message.amount.length !== 0) {
      writer.uint32(34).bytes(message.amount);
    }
    if (message.refTimeLimit !== 0) {
      writer.uint32(40).uint64(message.refTimeLimit);
    }
    if (message.allowReentry !== false) {
      writer.uint32(48).bool(message.allowReentry);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoCallContent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoCallContent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.contract = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.selector = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.input = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amount = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.refTimeLimit = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.allowReentry = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoCallContent>, I>>(base?: I): DaoCallContent {
    return DaoCallContent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoCallContent>, I>>(object: I): DaoCallContent {
    const message = createBaseDaoCallContent();
    message.contract = object.contract ?? new Uint8Array(0);
    message.selector = object.selector ?? new Uint8Array(0);
    message.input = object.input ?? new Uint8Array(0);
    message.amount = object.amount ?? new Uint8Array(0);
    message.refTimeLimit = object.refTimeLimit ?? 0;
    message.allowReentry = object.allowReentry ?? false;
    return message;
  },
};

function createBaseDaoInit(): DaoInit {
  return { initialMembers: [], publicJoin: false, sudoAccount: new Uint8Array(0), defaultTrack: undefined };
}

export const DaoInit: MessageFns<DaoInit> = {
  encode(message: DaoInit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.initialMembers) {
      DaoMember.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.publicJoin !== false) {
      writer.uint32(16).bool(message.publicJoin);
    }
    if (message.sudoAccount.length !== 0) {
      writer.uint32(26).bytes(message.sudoAccount);
    }
    if (message.defaultTrack !== undefined) {
      DaoTrackData.encode(message.defaultTrack, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoInit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoInit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.initialMembers.push(DaoMember.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.publicJoin = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sudoAccount = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.defaultTrack = DaoTrackData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoInit>, I>>(base?: I): DaoInit {
    return DaoInit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoInit>, I>>(object: I): DaoInit {
    const message = createBaseDaoInit();
    message.initialMembers = object.initialMembers?.map((e) => DaoMember.fromPartial(e)) || [];
    message.publicJoin = object.publicJoin ?? false;
    message.sudoAccount = object.sudoAccount ?? new Uint8Array(0);
    message.defaultTrack = (object.defaultTrack !== undefined && object.defaultTrack !== null)
      ? DaoTrackData.fromPartial(object.defaultTrack)
      : undefined;
    return message;
  },
};

function createBaseDaoPublicJoin(): DaoPublicJoin {
  return {};
}

export const DaoPublicJoin: MessageFns<DaoPublicJoin> = {
  encode(_: DaoPublicJoin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoPublicJoin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoPublicJoin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoPublicJoin>, I>>(base?: I): DaoPublicJoin {
    return DaoPublicJoin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoPublicJoin>, I>>(_: I): DaoPublicJoin {
    const message = createBaseDaoPublicJoin();
    return message;
  },
};

function createBaseDaoJoin(): DaoJoin {
  return { newUser: new Uint8Array(0), balance: new Uint8Array(0) };
}

export const DaoJoin: MessageFns<DaoJoin> = {
  encode(message: DaoJoin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.newUser.length !== 0) {
      writer.uint32(10).bytes(message.newUser);
    }
    if (message.balance.length !== 0) {
      writer.uint32(18).bytes(message.balance);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoJoin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoJoin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.newUser = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.balance = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoJoin>, I>>(base?: I): DaoJoin {
    return DaoJoin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoJoin>, I>>(object: I): DaoJoin {
    const message = createBaseDaoJoin();
    message.newUser = object.newUser ?? new Uint8Array(0);
    message.balance = object.balance ?? new Uint8Array(0);
    return message;
  },
};

function createBaseDaoLeave(): DaoLeave {
  return {};
}

export const DaoLeave: MessageFns<DaoLeave> = {
  encode(_: DaoLeave, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoLeave {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoLeave();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoLeave>, I>>(base?: I): DaoLeave {
    return DaoLeave.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoLeave>, I>>(_: I): DaoLeave {
    const message = createBaseDaoLeave();
    return message;
  },
};

function createBaseDaoLeaveWithBurn(): DaoLeaveWithBurn {
  return {};
}

export const DaoLeaveWithBurn: MessageFns<DaoLeaveWithBurn> = {
  encode(_: DaoLeaveWithBurn, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoLeaveWithBurn {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoLeaveWithBurn();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoLeaveWithBurn>, I>>(base?: I): DaoLeaveWithBurn {
    return DaoLeaveWithBurn.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoLeaveWithBurn>, I>>(_: I): DaoLeaveWithBurn {
    const message = createBaseDaoLeaveWithBurn();
    return message;
  },
};

function createBaseDaoSubmitProposal(): DaoSubmitProposal {
  return { call: undefined, trackId: 0 };
}

export const DaoSubmitProposal: MessageFns<DaoSubmitProposal> = {
  encode(message: DaoSubmitProposal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.call !== undefined) {
      DaoCallContent.encode(message.call, writer.uint32(10).fork()).join();
    }
    if (message.trackId !== 0) {
      writer.uint32(16).uint32(message.trackId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoSubmitProposal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoSubmitProposal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.call = DaoCallContent.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.trackId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoSubmitProposal>, I>>(base?: I): DaoSubmitProposal {
    return DaoSubmitProposal.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoSubmitProposal>, I>>(object: I): DaoSubmitProposal {
    const message = createBaseDaoSubmitProposal();
    message.call = (object.call !== undefined && object.call !== null)
      ? DaoCallContent.fromPartial(object.call)
      : undefined;
    message.trackId = object.trackId ?? 0;
    return message;
  },
};

function createBaseDaoDepositProposal(): DaoDepositProposal {
  return { proposalId: 0, amount: new Uint8Array(0) };
}

export const DaoDepositProposal: MessageFns<DaoDepositProposal> = {
  encode(message: DaoDepositProposal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.proposalId !== 0) {
      writer.uint32(8).uint32(message.proposalId);
    }
    if (message.amount.length !== 0) {
      writer.uint32(18).bytes(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoDepositProposal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoDepositProposal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.proposalId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amount = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoDepositProposal>, I>>(base?: I): DaoDepositProposal {
    return DaoDepositProposal.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoDepositProposal>, I>>(object: I): DaoDepositProposal {
    const message = createBaseDaoDepositProposal();
    message.proposalId = object.proposalId ?? 0;
    message.amount = object.amount ?? new Uint8Array(0);
    return message;
  },
};

function createBaseDaoSubmitVote(): DaoSubmitVote {
  return { proposalId: 0, opinionYes: false, lockAmount: new Uint8Array(0) };
}

export const DaoSubmitVote: MessageFns<DaoSubmitVote> = {
  encode(message: DaoSubmitVote, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.proposalId !== 0) {
      writer.uint32(8).uint32(message.proposalId);
    }
    if (message.opinionYes !== false) {
      writer.uint32(16).bool(message.opinionYes);
    }
    if (message.lockAmount.length !== 0) {
      writer.uint32(26).bytes(message.lockAmount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoSubmitVote {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoSubmitVote();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.proposalId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.opinionYes = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lockAmount = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoSubmitVote>, I>>(base?: I): DaoSubmitVote {
    return DaoSubmitVote.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoSubmitVote>, I>>(object: I): DaoSubmitVote {
    const message = createBaseDaoSubmitVote();
    message.proposalId = object.proposalId ?? 0;
    message.opinionYes = object.opinionYes ?? false;
    message.lockAmount = object.lockAmount ?? new Uint8Array(0);
    return message;
  },
};

function createBaseDaoCancelVote(): DaoCancelVote {
  return { voteId: 0 };
}

export const DaoCancelVote: MessageFns<DaoCancelVote> = {
  encode(message: DaoCancelVote, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.voteId !== 0) {
      writer.uint32(8).uint64(message.voteId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoCancelVote {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoCancelVote();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.voteId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoCancelVote>, I>>(base?: I): DaoCancelVote {
    return DaoCancelVote.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoCancelVote>, I>>(object: I): DaoCancelVote {
    const message = createBaseDaoCancelVote();
    message.voteId = object.voteId ?? 0;
    return message;
  },
};

function createBaseDaoUnlock(): DaoUnlock {
  return { voteId: 0 };
}

export const DaoUnlock: MessageFns<DaoUnlock> = {
  encode(message: DaoUnlock, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.voteId !== 0) {
      writer.uint32(8).uint64(message.voteId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoUnlock {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoUnlock();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.voteId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoUnlock>, I>>(base?: I): DaoUnlock {
    return DaoUnlock.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoUnlock>, I>>(object: I): DaoUnlock {
    const message = createBaseDaoUnlock();
    message.voteId = object.voteId ?? 0;
    return message;
  },
};

function createBaseDaoExecProposal(): DaoExecProposal {
  return { proposalId: 0 };
}

export const DaoExecProposal: MessageFns<DaoExecProposal> = {
  encode(message: DaoExecProposal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.proposalId !== 0) {
      writer.uint32(8).uint32(message.proposalId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoExecProposal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoExecProposal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.proposalId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoExecProposal>, I>>(base?: I): DaoExecProposal {
    return DaoExecProposal.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoExecProposal>, I>>(object: I): DaoExecProposal {
    const message = createBaseDaoExecProposal();
    message.proposalId = object.proposalId ?? 0;
    return message;
  },
};

function createBaseDaoCancelProposal(): DaoCancelProposal {
  return { proposalId: 0 };
}

export const DaoCancelProposal: MessageFns<DaoCancelProposal> = {
  encode(message: DaoCancelProposal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.proposalId !== 0) {
      writer.uint32(8).uint32(message.proposalId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoCancelProposal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoCancelProposal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.proposalId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoCancelProposal>, I>>(base?: I): DaoCancelProposal {
    return DaoCancelProposal.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoCancelProposal>, I>>(object: I): DaoCancelProposal {
    const message = createBaseDaoCancelProposal();
    message.proposalId = object.proposalId ?? 0;
    return message;
  },
};

function createBaseDaoTransfer(): DaoTransfer {
  return { to: new Uint8Array(0), value: new Uint8Array(0) };
}

export const DaoTransfer: MessageFns<DaoTransfer> = {
  encode(message: DaoTransfer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to.length !== 0) {
      writer.uint32(10).bytes(message.to);
    }
    if (message.value.length !== 0) {
      writer.uint32(18).bytes(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoTransfer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoTransfer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.to = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoTransfer>, I>>(base?: I): DaoTransfer {
    return DaoTransfer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoTransfer>, I>>(object: I): DaoTransfer {
    const message = createBaseDaoTransfer();
    message.to = object.to ?? new Uint8Array(0);
    message.value = object.value ?? new Uint8Array(0);
    return message;
  },
};

function createBaseDaoApprove(): DaoApprove {
  return { spender: new Uint8Array(0), value: new Uint8Array(0) };
}

export const DaoApprove: MessageFns<DaoApprove> = {
  encode(message: DaoApprove, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.spender.length !== 0) {
      writer.uint32(10).bytes(message.spender);
    }
    if (message.value.length !== 0) {
      writer.uint32(18).bytes(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoApprove {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoApprove();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.spender = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoApprove>, I>>(base?: I): DaoApprove {
    return DaoApprove.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoApprove>, I>>(object: I): DaoApprove {
    const message = createBaseDaoApprove();
    message.spender = object.spender ?? new Uint8Array(0);
    message.value = object.value ?? new Uint8Array(0);
    return message;
  },
};

function createBaseDaoTransferFrom(): DaoTransferFrom {
  return { from: new Uint8Array(0), to: new Uint8Array(0), value: new Uint8Array(0) };
}

export const DaoTransferFrom: MessageFns<DaoTransferFrom> = {
  encode(message: DaoTransferFrom, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from.length !== 0) {
      writer.uint32(10).bytes(message.from);
    }
    if (message.to.length !== 0) {
      writer.uint32(18).bytes(message.to);
    }
    if (message.value.length !== 0) {
      writer.uint32(26).bytes(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoTransferFrom {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoTransferFrom();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.to = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.value = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoTransferFrom>, I>>(base?: I): DaoTransferFrom {
    return DaoTransferFrom.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoTransferFrom>, I>>(object: I): DaoTransferFrom {
    const message = createBaseDaoTransferFrom();
    message.from = object.from ?? new Uint8Array(0);
    message.to = object.to ?? new Uint8Array(0);
    message.value = object.value ?? new Uint8Array(0);
    return message;
  },
};

function createBaseDaoSpend(): DaoSpend {
  return { to: new Uint8Array(0), amount: new Uint8Array(0), trackId: 0 };
}

export const DaoSpend: MessageFns<DaoSpend> = {
  encode(message: DaoSpend, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to.length !== 0) {
      writer.uint32(10).bytes(message.to);
    }
    if (message.amount.length !== 0) {
      writer.uint32(18).bytes(message.amount);
    }
    if (message.trackId !== 0) {
      writer.uint32(24).uint32(message.trackId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoSpend {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoSpend();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.to = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amount = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.trackId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoSpend>, I>>(base?: I): DaoSpend {
    return DaoSpend.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoSpend>, I>>(object: I): DaoSpend {
    const message = createBaseDaoSpend();
    message.to = object.to ?? new Uint8Array(0);
    message.amount = object.amount ?? new Uint8Array(0);
    message.trackId = object.trackId ?? 0;
    return message;
  },
};

function createBaseDaoPayout(): DaoPayout {
  return { spendId: 0 };
}

export const DaoPayout: MessageFns<DaoPayout> = {
  encode(message: DaoPayout, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.spendId !== 0) {
      writer.uint32(8).uint64(message.spendId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoPayout {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoPayout();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.spendId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoPayout>, I>>(base?: I): DaoPayout {
    return DaoPayout.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoPayout>, I>>(object: I): DaoPayout {
    const message = createBaseDaoPayout();
    message.spendId = object.spendId ?? 0;
    return message;
  },
};

function createBaseDaoSetPublicJoin(): DaoSetPublicJoin {
  return { publicJoin: false };
}

export const DaoSetPublicJoin: MessageFns<DaoSetPublicJoin> = {
  encode(message: DaoSetPublicJoin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.publicJoin !== false) {
      writer.uint32(8).bool(message.publicJoin);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoSetPublicJoin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoSetPublicJoin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.publicJoin = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoSetPublicJoin>, I>>(base?: I): DaoSetPublicJoin {
    return DaoSetPublicJoin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoSetPublicJoin>, I>>(object: I): DaoSetPublicJoin {
    const message = createBaseDaoSetPublicJoin();
    message.publicJoin = object.publicJoin ?? false;
    return message;
  },
};

function createBaseDaoAddTrack(): DaoAddTrack {
  return { track: undefined };
}

export const DaoAddTrack: MessageFns<DaoAddTrack> = {
  encode(message: DaoAddTrack, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.track !== undefined) {
      DaoTrackData.encode(message.track, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoAddTrack {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoAddTrack();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.track = DaoTrackData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoAddTrack>, I>>(base?: I): DaoAddTrack {
    return DaoAddTrack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoAddTrack>, I>>(object: I): DaoAddTrack {
    const message = createBaseDaoAddTrack();
    message.track = (object.track !== undefined && object.track !== null)
      ? DaoTrackData.fromPartial(object.track)
      : undefined;
    return message;
  },
};

function createBaseDaoSetDefaultTrack(): DaoSetDefaultTrack {
  return { trackId: 0 };
}

export const DaoSetDefaultTrack: MessageFns<DaoSetDefaultTrack> = {
  encode(message: DaoSetDefaultTrack, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trackId !== 0) {
      writer.uint32(8).uint32(message.trackId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DaoSetDefaultTrack {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDaoSetDefaultTrack();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.trackId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DaoSetDefaultTrack>, I>>(base?: I): DaoSetDefaultTrack {
    return DaoSetDefaultTrack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DaoSetDefaultTrack>, I>>(object: I): DaoSetDefaultTrack {
    const message = createBaseDaoSetDefaultTrack();
    message.trackId = object.trackId ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
