export default {
  tokenEconomy: 'Token Economy',
  fairLaunch: 'Fair Launch',
  crossChain: 'Cross Chain',
  economy: {
    title: 'TOKEN Mechanism',
    heroHtml:
      'This protocol <strong>does not issue any token</strong>. The only governance token is <strong>VOTE</strong>, used for governance voting.' +
      ' VOTE is not used for payments, dividends, or any asset promise; it only measures voting power.',
    usage: {
      title: 'What VOTE is for',
      bodyHtml:
        'Governance voting only (OpenGov / proposal voting, etc.).<br />Not for payments, trading, staking rewards, GAS, or any settlement.',
    },
    voteSplit: {
      title: 'How VOTE is generated & distributed (per consumption)',
      table: {
        party: 'Party',
        vote: 'VOTE received',
        desc: 'Description',
      },
      rows: {
        consumer: {
          party: 'Consumer (payer)',
          vote: '2× VOTE',
          desc: 'Every consumption generates VOTE. Consumers receive 2× VOTE for governance participation.',
        },
        compute: {
          party: 'Compute node (executor)',
          vote: '1× VOTE',
          desc: 'Nodes that provide compute and complete tasks/services receive VOTE.',
        },
        consensus: {
          party: 'Consensus packager node',
          vote: 'Tx VOTE × 1/3',
          desc: 'After the transaction is packaged, the packager consensus node receives a fixed VOTE amount (Tx VOTE × 1/3).',
        },
      },
      note:
        '"Tx VOTE" means the base VOTE generated by this consumption (consumer gets 2× and compute node gets 1×, so Tx VOTE = 2× + 1×). ' +
        'Exact metering and parameters follow on-chain rules and the dApp display.',
      legend: {
        consumer: 'Consumer',
        compute: 'Compute node',
        consensus: 'Consensus packager',
      },
    },
    fees: {
      title: 'On-chain protocol revenue & fee distribution',
      bodyHtml:
        'The protocol charges a <strong>fee</strong> on user payments as on-chain protocol revenue.<br />' +
        'Fees are distributed as:<br />' +
        '- <strong>50%</strong>: to the Treasury<br />' +
        '- <strong>50%</strong>: directly to the consensus node that securely packages the transaction (packager)',
    },
    treasury: {
      title: 'Treasury governance',
      bodyHtml: 'The Treasury is managed in a <strong>decentralized</strong> way through community OpenGov proposals, voting, and execution.',
    },
    govRole: {
      title: 'VOTE in governance',
      bodyHtml:
        'VOTE measures governance voting power. Governance participation can influence (not limited to):<br />' +
        '- Treasury spending and allocation<br />' +
        '- On-chain protocol parameter changes and upgrades<br />' +
        '- Proposals, referenda, and track-based voting<br />' +
        '<br />' +
        '<strong>Important:</strong> once you use VOTE to vote in governance, the voted VOTE will be <strong>permanently locked</strong> (cannot be unlocked or returned to available balance).',
    },
  },
}
